# Generated by Django 6.0.2 on 2026-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_type', models.CharField(choices=[('network', 'Network Printer (IP:Port)'), ('windows', 'Windows Shared Printer')], default='network', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Required for network printer', null=True)),
                ('port', models.IntegerField(default=9100, help_text='Port for network printer')),
                ('printer_name', models.CharField(blank=True, help_text="Windows printer name (e.g., 'Xprinter XP-80C')", max_length=255)),
                ('paper_width', models.IntegerField(default=80, help_text='Paper width in mm')),
                ('logo_text', models.CharField(default='My School', help_text='Header text', max_length=255)),
                ('school_name', models.CharField(default='Private School', max_length=255)),
                ('school_address', models.CharField(blank=True, max_length=255)),
                ('school_phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Printer Configuration',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_printer_config')],
            },
        ),
    ]
